### ISSUE TITLE
🐞 [Bug] - 추가 예외 처리 필요 항목

### ISSUE THREAD

**Issue by yes-ee** [yes-ee/irc#4]
## 🕵🏻 Condition
예외 처리가 필요한 항목 작성

## 📝 Description
- 아래 To-Do에 추가
- 이슈로 처리 후 To-do에서 완료 체크하기

## ✅ To-do
- [x] port int 아닌 경우 예외 처리
- [x] 인자로 들어오는 password 길이 제한 예외 처리
- [x] PASS 비밀번호 안 맞으면 연결 끊기
- [x] WHO 채널 조회 시 비공개방 여부 확인
