### ISSUE TITLE
✨ [Feat] - Method Parsing

### ISSUE THREAD

**Issue by chobinee** [yes-ee/irc#7]
## 📝 Description
- irc 메소드 파싱

## ✅ To-do
- [x] CAP
- [x] Authenticate
- [x] Pass : server password 확인
- [x] Nick : nickname 변경
- [x] User : username 변경
- [x] Ping : 클라이언트-서버 간 연결 확인
- [x] Quit : 클라이언트 연결 종료
- [x] Error
- [x] Who
- [x] Join : 채널 입장
- [x] Topic
- [x] List : 현재 서버에서 사용 가능한 채널 목록 조회
- [x] Invite : 다른 클라이언트 채널에 초대
- [x] Kick : 클라이언트 특정 채널에서 내보냄
- [x] Mode
- [x] Part : 채널에서 나감
- [x] Privmsg : 특정 사용자 또는 채널에 메시지 보냄

## 📚 Etc
- 어려우려나...?
